name: Create git actions

on: 
  push:
     branches: 
       - main

jobs:
  myjob:
      runs-on: ubuntu-latest
      
      steps:
          - name: Checkout repository
            run: |
                  echo "Devops is Fun! Do you agree? " > messages.txt
          - name: Multi line step
            run: |
              pwd
              cat messages.txt
              echo "This is my message"
#   print_working_directory:
#            runs-on: ubuntu-latest
           
#            steps:
#               - name: print current working directory
#                 run: pwd
                   
#   display_message_content:
#             runs-on: ubuntu-latest
            
#             steps:
#                - name: checkout repository
#                  run: cat messages.txt
      # - name: <step 2>
      #   run: |
      #     <commands>
